### ISSUE TITLE
error: module not found

### ISSUE THREAD

**Issue by rashaverak** [beryx/badass-jlink-plugin#61] opened 2019-06-04 12:22 UTC
in my dependencies

`implementation 'javax.xml.ws:jaxws-api:2.3.1'`

in my module-info.java

`requires java.xml.ws;`

alright, found, when I ctrl click on it I got to its module-info which starts with

```
module java.xml.ws {
    requires java.xml.bind;
    exports javax.xml.ws;
```

I can sucessfully run the run and jar tasks but when I run jlink task of your plugin

> Task :compileJava UP-TO-DATE
> Task :processResources UP-TO-DATE
> Task :classes UP-TO-DATE
> Task :libs UP-TO-DATE
> Task :jar UP-TO-DATE
> Task :prepareMergedJarsDir UP-TO-DATE

> Task :createMergedModule
Cannot derive uses clause from service loader invocation in: com/fasterxml/jackson/databind/ObjectMapper.secureGetServiceLoader().
Cannot derive uses clause from service loader invocation in: com/fasterxml/jackson/databind/ObjectMapper$2.run().
Cannot derive uses clause from service loader invocation in: org/apache/commons/compress/utils/ServiceLoaderIterator.<init>().
/build/jlinkbase/tmpjars/.../module-info.java:426: error: module not found: java.xml.bind
    requires java.xml.bind;
                     ^
/build/jlinkbase/tmpjars/.../module-info.java:427: error: module not found: java.xml.ws
    requires java.xml.ws;

I guess the issue might be that the module java.xml.ws exports javax.xml.ws ?
Anyway, do you have idea how to overcome this issue ?

**Comment by siordache** [comment] 2019-06-04 12:59
Try adding the following to your Gradle build script:

    dependencies {
        implementation 'org.glassfish.jaxb:jaxb-runtime:2.3.2'
        implementation 'javax.annotation:javax.annotation-api:1.3.2'
        ...
    }
    
    
    jlink {
        forceMerge 'jaxws'
        ...
    }

**Comment by tobiasdiez** [comment] 2019-06-04 21:42
I have the same problem:
````
\build\jlinkbase\tmpjars\org.jabref.merged.module\module-info.java:1097: error: module not found: org.controlsfx.controls
    requires org.controlsfx.controls;
                           ^
\build\jlinkbase\tmpjars\org.jabref.merged.module\module-info.java:1103: error: module not found: org.bouncycastle.provider
    requires org.bouncycastle.provider;
                             ^
\build\jlinkbase\tmpjars\org.jabref.merged.module\module-info.java:1108: error: module not found: java.xml.bind
    requires java.xml.bind;
````
The complete build.gradle file can be found here: https://github.com/JabRef/jabref/blob/jdk9/build.gradle
I tried to add
````
    forceMerge "org.controlsfx.controls"
    forceMerge "org.bouncycastle.provider"
    forceMerge "java.xml.bind"
````
to the `jlink` task, but that didn't worked. What is the correct argument for `forceMerge` ?

**Comment by siordache** [comment] 2019-06-05 12:30
@tobiasdiez It was a bit more complicated than I expected. I submitted my changes [as a PR](https://github.com/JabRef/jabref/pull/5032). Below are a few explanations.


The arguments of `forceMerge` are prefixes of the JAR file names to be merged.  For example, the JAR file associated with `org.bouncycastle:bcprov-jdk15on:1.61` is `bcprov-jdk15on-1.61.jar`, so we can pass the `bcprov` prefix to forceMerge.


In build.gradle I replaced:

    forceMerge "org.controlsfx.controls"
    forceMerge "org.bouncycastle.provider"
    forceMerge "java.xml.bind"
    
with:    
    
    forceMerge "controlsfx", "bcprov", "jaxb", "javax", "istack", "stax", "log4j"


The module descriptor automatically generated by the plugin for the merged module contained some invalid entries, so I added a `mergedModule` block. I did this by executing `./gradlew suggestMergedModuleInfo`, removing the incorrect directives from the suggested `mergedModule` block and including it in build.gradle.

It was also necessary to start the application using a launcher class that doesn't extend Application (see [this discussion](http://mail.openjdk.java.net/pipermail/openjfx-dev/2018-June/021977.html)).

When executing the custom running image, ThemeLoader.addAndWatchForChanges throws an UnsupportedOperationException. My quick and dirty workaround was to catch this exception.

**Comment by rashaverak** [comment] 2019-06-06 06:21
I did not have luck with the proposed solution as well because by adding the 2 proposed libs to dependencies I got a lot of duplicate modules errors while java compiled. As I have pretty big project I am trying to update and put to shape, I was able to get rid of the dependancy causing the issue completely. It only let to just another issue. Will try to solve it and if unable I will start another issue.

**Comment by kmp1** [comment] 2019-06-21 08:03
Hi,

I don't know if this is the same root cause but I'm also having errors about missing module **javafx.base**, **javafx.controls** and **javafx.graphics** and would really appreciate some help.

I did this:

> git clone https://github.com/beryx-gist/badass-jlink-example-log4j2-javafx.git

> cd badass-jlink-example-log4j2-javafx

...edited the build.gradle and module-info.java to pick up richtextfx (I also get the same problem rxjavafx too)...
> git diff

```
diff --git a/build.gradle b/build.gradle
index 0e92a19..81bc69f 100644
--- a/build.gradle
+++ b/build.gradle
@@ -10,6 +10,7 @@ repositories {

 dependencies {
     compile 'org.apache.logging.log4j:log4j-core:2.11.1'
+    compile group: 'org.fxmisc.richtext', name: 'richtextfx', version: '0.10.1'
 }

 javafx {
diff --git a/src/main/java/module-info.java b/src/main/java/module-info.java
index 06330ba..dab2c2a 100644
--- a/src/main/java/module-info.java
+++ b/src/main/java/module-info.java
@@ -1,6 +1,7 @@
 module hellofx {
     requires javafx.controls;
     requires org.apache.logging.log4j;
+    requires richtextfx;

     exports org.openjfx;
 }
```

> gradlew jlink
```

> Configure project :
Found module name 'hellofx'

> Task :createMergedModule
Picked up _JAVA_OPTIONS: -Djava.net.preferIPv4Stack=true
Picked up _JAVA_OPTIONS: -Djava.net.preferIPv4Stack=true
C:\dev\code\sandpit\badass-jlink-example-log4j2-javafx\build\jlinkbase\tmpjars\hellofx.merged.module\module-info.java:79: error: module not found: javafx.graphics
    requires javafx.graphics;
                   ^
C:\dev\code\sandpit\badass-jlink-example-log4j2-javafx\build\jlinkbase\tmpjars\hellofx.merged.module\module-info.java:81: error: module not found: javafx.controls
    requires javafx.controls;
                   ^
C:\dev\code\sandpit\badass-jlink-example-log4j2-javafx\build\jlinkbase\tmpjars\hellofx.merged.module\module-info.java:89: error: module not found: javafx.base
    requires javafx.base;
                   ^
3 errors

> Task :createMergedModule FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':createMergedModule'.
> Process 'command 'c:\Program Files\Java\jdk-11.0.2/bin/javac'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 27s
5 actionable tasks: 3 executed, 2 up-to-date
```

I tried various things in the `forceMerge` option but could not find a magic formula.  Is this a problem that needs to be resolved in, for example, the richtextfx library and not here perhaps?  I'm not really sure where to start debugging this...

**Comment by siordache** [comment] 2019-06-22 07:31
@kmp1 The POM of the richtextfx library does not declare the JavaFX dependencies,. To inform the plugin about these dependencies you need to call the [addExtraDependencies](https://badass-jlink-plugin.beryx.org/releases/latest/#_methods) method in your `jlink` block:

```
jlink {
    ...
    addExtraDependencies("javafx")
    ...
}
```

See [this RichTextFX project](https://github.com/beryx-gist/badass-jlink-example-richtextfx) for an example.

**Comment by kmp1** [comment] 2019-06-24 06:45
@siordache THANK YOU!  Perfect, worked fine.

**Closed** 2019-06-30 22:20 UTC
