### ISSUE TITLE
Issues with the new customImage block

### ISSUE THREAD

**Issue by nemphys** [beryx/badass-jlink-plugin#73] opened 2019-07-29 10:43 UTC
Since I have been waiting for this functionality for a long time, I was delighted to see it implemented and started playing with it as soon as the latest version was released.

The first issue I am facing is that there seems to be a problem with the core modules requirement detection before running jlink. By just adding the customImage block in the configuration (with jdkModules null and appModules either null/empty array or populated with the merged module), jlink fails to produce an image due to missing core modules. After manually including the missing core modules using a jlink '--add-modules' option (it would be nice to have an option to *add* some extra modules to the automatically-generated ones instead of having to set the full list with jdkModules), the image is successfully built, but the result does not contain the javafx native libraries (and is therefore not runnable).

My goal is to build an image with *only* the core java modules + the javafx modules/libraries and have *all* the application modules (proper java 9 modules + merged module) inside the "app" directory.

Did I miss something in the configuration, or is this a bug?

Edit: After manually adding the required javafx modules list using '--add-modules', the javafx libraries are properly included in the resulting jlink image (which makes sense), but the javafx jar files are also copied to the 'app' directory (which also makes sense, but leads to double content).

**Comment by siordache** [comment] 2019-07-29 19:25
It's probably a bug, because the plugin should take care of everything and the use of `--add-modules` should never be necessary. For example, [here](https://github.com/beryx-gist/badass-jlink-example-richtextfx/blob/cb18f2091cc8d3f9179cd9ddac36fb32ddd54b40/build.gradle#L36-L38) is how I configured the Gradle script of _badass-jlink-example-richtextfx_ to create a custom image containing only the core and javafx modules:

```
customImage {
    appModules = ['javafx.base', 'javafx.controls', 'javafx.graphics']
}
```


Which required core modules were missed by the plugin in your case? You can see which modules have been included in the custom image (that is, in the big `modules` file) by executing:
```
jimage list build/image/lib/modules | grep "Module:"
```


> it would be nice to have an option to add some extra modules  to the automatically-generated ones instead of having to set the full list with jdkModules

That's a good idea. I will provide such an option in the next release. In the meantime, you can see the list of core modules detected by the plugin by executing the `suggestMergedModuleInfo` task. (The `customImage` block should be present in your build script.)
For example, for the _badass-jlink-example-richtextfx_ application, this task prints:

```
customImage {
    jdkModules = [java.desktop, java.xml, jdk.unsupported]
}
```


It's difficult to analyze this issue without seeing some code. Can you make your project available on GitHub? Or maybe provide a simple example application that reproduces your problem? Or at least post your build.gradle and module-info.java along with the output of executing gradle with the --info option?

**Comment by nemphys** [comment] 2019-07-29 21:06
Thank you for the fast response.

I will try again adding the javafx modules to the appModules option as you suggest (I thought it would not be necessary to do that; will the auto-detected core modules be included if I just enter the javafx modules in this option?) and report back, although I am afraid it will include the javafx modules both in the image modules file and as separate jars in the app directory.

The missing core modules were: jdk.localedata,jdk.javadoc,java.instrument,java.rmi,jdk.attach,java.management and I think they were all required by ScenicView (https://github.com/JonathanGiles/scenic-view), which is included in the project as a precompiled jar (not as a gradle package dependency).

One more strange thing that went wrong was that the org.slf4j module (which is now a proper Java9 module) was not copied to the app directory inside the produced image, even though it exists in the jlinkjars build directory. I had to manually copy it after the build, otherwise the application would not start.

I totally understand that it is difficult to debug without some source/info, but I am afraid it is not possible to share anything, since this is an internal company project.

**Comment by nemphys** [comment] 2019-07-30 13:51
I tried it with the jdkModules (not appModules, it was a typo) option populated with the javafx modules and, indeed, the modules are included in the image and not copied to the app directory.

I also managed to make an image by manually specifying all the required core modules, but I would prefer it if they were automatically detected (properly).

Still, org.slf4j is missing, though.

One more thing that looks weird is that only *some* (around 3/10) of the delegating module jars are copied to the final app directory. The application runs fine, but I would appreciate it if you explained the logic behind the selection.

**Comment by siordache** [comment] 2019-07-30 16:08
> I tried it with the jdkModules (not appModules, it was a typo) option populated with the javafx modules and, indeed, the modules are included in the image and not copied to the app directory.

Do you use a JDK distribution that also contains the javafx modules? Otherwise, the javafx modules should appear in the `appModules` list, since they are no longer part of the JDK.


I just released 2.14.0, which should fix the problem of org.slf4j and other modules not being copied to the app directory. It also introduces the boolean property `jdkAdditive`. If this property is true, the modules in the `jdkModules` list will be added to the list of required JDK plugins detected by the plugin itself.

So, your customImage block should be something like this:

```
customImage {
    jdkAdditive = true
    jdkModules = ['jdk.localedata', 'jdk.javadoc', 'java.instrument', 'java.rmi', 'jdk.attach', 'java.management']
    appModules = ['javafx.base', 'javafx.controls', 'javafx.graphics']
}
```

(But if your JDK distribution also contains the javafx modules, then put everything in the `jdkModules` list.)

**Comment by nemphys** [comment] 2019-07-30 18:13
Ultra-fast as always :-)

I am using OpenJDK 11.0.2 along with the JavaFX 13ea jmods (not included).

Just to get this straight: if I want the javafx modules in the image, where do I have to declare them, in jdkModules or in appModules?

I will test the new changes later tonight and report back.

**Comment by siordache** [comment] 2019-07-30 21:52
I'm not sure if it helps, but try this: 

- remove the `requires org.slf4j` from `mergedModule`
- add `forceMerge 'slf4j'` to the `jlink` block (the argument of forceMerge is a prefix of the name of the JAR file containing the org.slf4j module)

This way, the plugin will treat slf4j as non-modular and it will include it in the merged module.  So, slf4j will still not be copied in the app directory (which is ok, because now it is part of the merged module) but the application should no longer throw an error.

**Comment by nemphys** [comment] 2019-07-31 10:18
Right, I considered doing that, but I am trying to keep as many jars outside the merged module as possible. For the time being, I just added a script that copies the jar to the app directory.

**Closed** 2019-12-19 11:57 UTC
