### ISSUE TITLE
JavaFx Koltin Project jpackage's msi Failed to launch JVM

### ISSUE THREAD

**Issue by myfaverate** [beryx/badass-jlink-plugin#285] opened 2024-12-19 13:56 UTC
## This is my github repository address
https://github.com/myfaverate/JavaFxKotlin
###  2. double-click installation
**path:** `build/jpackage/template-1.0.msi`
### click desktop icon
**result:**
![QQ_1734616512030](https://github.com/user-attachments/assets/ab76bb4e-8400-4023-9dd8-e1c1751c70f7)

**Comment by xzel23** [comment] 2024-12-22 04:01
I am not on Windows, so I could not try the MSI part. But I checked your project out and built on macOS and can reproduce the error of the JVM not being able to start from the jpackage image. To resolve such problems, run the launcher directly from the console as you will get a more detailed error message:

```
% ./build/jpackage/template.app/Contents/MacOS/template 
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.InternalError: Module edu.tyut.template not in boot Layer
        at java.base/sun.launcher.LauncherHelper.loadModuleMainClass(Unknown Source)
        at java.base/sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
Failed to launch JVM
```

So, your application class is not contained in the merged module. I renamed the module to simply `template` to make it distinct from the package `edu.tyut.template`:

```
module edu.tyut.template {
    ...
}
```

becomes
```
module template {
    ...
}
```

and of course I had to change the module name in `build.kts` too, so I changed
```
application {
    mainModule.set("edu.tyut.template")
    mainClass.set("edu.tyut.template.HelloApplicationKt")
}
```

to

```
application {
    mainModule.set("template")
    mainClass.set("edu.tyut.template.HelloApplicationKt")
}
```

and it works. I don't know if the problem is with the Badass JLink plugin itself, the modularity plugin, or  the combination of both.

Please try and see if these changes work for your windows MSI installer too and report back.

**Comment by myfaverate** [comment] 2024-12-22 04:43
It works,  Thank you very much! 😊

**Closed** 2024-12-22 11:12 UTC
