### ISSUE TITLE
Wrong mergedjars directory

### ISSUE THREAD

**Issue by Burtan** [beryx/badass-jlink-plugin#2] opened 2018-09-09 18:22 UTC
Hi,
I've taken a look at the code and it seems that the mergedjars dir is incorrect.

mergedjars:
```
mergedJarsDir.set(project.layout.buildDirectory.dir(PathUtil.getMergedJarsDirPath(jlinkBasePath.get())))
```
delegatedModulesDir
```delegatedModulesDir.set(new File(PathUtil.getDelegatedModulesDirPath(jlinkBasePath.get())))```

nonModularJarsDir
```nonModularJarsDir.set(new File(PathUtil.getNonModularJarsDirPath(jlinkBasePath.get())))```

**Comment by siordache** [comment] 2018-09-10 20:56
I'm not able to reproduce your problem. Can you make your project available in a public repository?
If this is not possible, I need at least your build.gradle file and the output of running gradle with `--info --stacktrace`.
But, of course, making your project available in a public repository would be much, much better.

**Comment by siordache** [comment] 2018-09-20 16:21
@Burtan Do you still get this error?
If yes, can you provide more details to help me reproduce it?

**Comment by Burtan** [comment] 2018-09-20 18:52
I think it has to do with kotlin. I'll post some more details or a small sample on the weekends!

**Comment by Burtan** [comment] 2018-09-23 07:50
I created a pull request with a small kotlin test project

**Comment by siordache** [comment] 2018-09-23 21:49
Fixed in release 1.4.4.

**Closed by siordache** 2018-09-23 21:49 UTC
Labels: bug
